// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydqktqcpspzrmykxazab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkcWt0cWNwc3B6cm15a3hhemFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDIyNDksImV4cCI6MjA2OTUxODI0OX0.ZtXi4KngvXbFcgG2Ppy67CxJMFZRXFi8b7ozsfTpZnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});